package io.github.mumu12641.lark.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF44655A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC6EADD)
val md_theme_light_onPrimaryContainer = Color(0xFF002019)
val md_theme_light_secondary = Color(0xFF59605D)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDDE4E0)
val md_theme_light_onSecondaryContainer = Color(0xFF161D1A)
val md_theme_light_tertiary = Color(0xFF566067)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDAE4EC)
val md_theme_light_onTertiaryContainer = Color(0xFF141D23)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFCFA)
val md_theme_light_onBackground = Color(0xFF1B1C1B)
val md_theme_light_surface = Color(0xFFFEFCFA)
val md_theme_light_onSurface = Color(0xFF1B1C1B)
val md_theme_light_surfaceVariant = Color(0xFFE2E3E0)
val md_theme_light_onSurfaceVariant = Color(0xFF454746)
val md_theme_light_outline = Color(0xFF757876)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_inverseSurface = Color(0xFF303030)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0EF)
val md_theme_light_inversePrimary = Color(0xFFABCEC1)
val md_theme_light_surfaceTint = Color(0xFF44655A)
val md_theme_light_surfaceTintColor = Color(0xFF44655A)

val md_theme_dark_primary = Color(0xFFABCEC1)
val md_theme_dark_onPrimary = Color(0xFF15362D)
val md_theme_dark_primaryContainer = Color(0xFF2D4D43)
val md_theme_dark_onPrimaryContainer = Color(0xFFC6EADD)
val md_theme_dark_secondary = Color(0xFFC1C8C4)
val md_theme_dark_onSecondary = Color(0xFF2B322F)
val md_theme_dark_secondaryContainer = Color(0xFF414845)
val md_theme_dark_onSecondaryContainer = Color(0xFFDDE4E0)
val md_theme_dark_tertiary = Color(0xFFBEC8D0)
val md_theme_dark_onTertiary = Color(0xFF283238)
val md_theme_dark_tertiaryContainer = Color(0xFF3F484F)
val md_theme_dark_onTertiaryContainer = Color(0xFFDAE4EC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF1B1C1B)
val md_theme_dark_onBackground = Color(0xFFE4E2E1)
val md_theme_dark_surface = Color(0xFF1B1C1B)
val md_theme_dark_onSurface = Color(0xFFE4E2E1)
val md_theme_dark_surfaceVariant = Color(0xFF454746)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C7C4)
val md_theme_dark_outline = Color(0xFF8F918F)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_inverseSurface = Color(0xFFE4E2E1)
val md_theme_dark_inverseOnSurface = Color(0xFF303030)
val md_theme_dark_inversePrimary = Color(0xFF44655A)
val md_theme_dark_surfaceTint = Color(0xFFABCEC1)
val md_theme_dark_surfaceTintColor = Color(0xFFABCEC1)


val seed = Color(0xFF00221A)